use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Token {
    pub type_: TokenType,
    pub lexeme: String,
    pub line: usize,
}

impl Token {
    pub fn new(token_type: TokenType, lexeme: String, line: usize) -> Self {
        Token {
            type_: token_type,
            lexeme,
            line,
        }
    }
}

impl Token {
    pub fn literal_as_string(&self) -> Option<String> {
        match &self.type_ {
            TokenType::String(val) => Some(val.clone()),
            TokenType::Number(val) => Some(val.to_string()),
            _ => None,
        }
    }
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let literal = match self.literal_as_string() {
            Some(val) => val,
            None => String::new(),
        };

        write!(
            f,
            "Token( {:?}, ({}), {} ) at line {}",
            self.type_, literal, self.lexeme, self.line
        )
    }
}

#[derive(Debug, Clone)]
pub enum TokenType {
    // Single-character tokens.
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    Comma,
    Dot,
    Minus,
    Plus,
    Semicolon,
    Slash,
    Star,

    // One or two character tokens.
    Bang,
    BangEqual,
    Equal,
    EqualEqual,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,

    // Literals.
    Identifier,
    String(String),
    Number(f64),

    // Keywords.
    And,
    Class,
    Else,
    False,
    Fun,
    For,
    If,
    Nil,
    Or,
    Print,
    Return,
    Super,
    This,
    True,
    Var,
    While,

    EOF,
}

impl TokenType {
    pub fn into_tok(self, ln: usize) -> Token {
        let lexeme = match &self {
            Self::Number(n) => n.to_string(),
            Self::String(s) => s.clone(),
            other => format!("{:?}", other).to_lowercase(),
        };

        Token {
            type_: self,
            lexeme,
            line: ln,
        }
    }
}

// generated by AI

impl PartialEq for TokenType {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (TokenType::Number(a), TokenType::Number(b)) => a.to_bits() == b.to_bits(),
            (TokenType::String(a), TokenType::String(b)) => a == b,
            (TokenType::Number(_), _) => false,
            (TokenType::String(_), _) => false,
            (_, TokenType::Number(_)) => false,
            (_, TokenType::String(_)) => false,
            _ => std::mem::discriminant(self) == std::mem::discriminant(other),
        }
    }
}

impl Eq for TokenType {}

impl std::hash::Hash for TokenType {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        std::mem::discriminant(self).hash(state);
        match self {
            TokenType::Number(n) => n.to_bits().hash(state),
            TokenType::String(s) => s.hash(state),
            _ => {}
        }
    }
}
